dist: bionic
language: julia

before_install:
  - sudo add-apt-repository ppa:anbe/opencl
  - sudo apt-get update
  - sudo apt-get install pocl -y

julia:
  - 1.2

notifications:
  email: false

jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate();
                                    Pkg.develop(PackageSpec(path=pwd()));'
        - julia --project=docs/ docs/make.jl
      after_success: skip
