name: TagBot
on:
  issue_comment:
    types: [created]
  schedule:
    - cron: '10 7 * * *'
  workflow_dispatch:
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: skleinbo/JuliaRegistry.jl
          lookback: 21
