name: Julia TagBot
on:
  issue_comment:
    types: 
      - created
  workflow_dispatch:
jobs:
  TagBot:
    if: github.event_name == 'workflow_dispatch' || github.actor == 'JuliaTagBot'
    runs-on: ubuntu-latest
    steps:
      - uses: JuliaRegistries/TagBot@v1
        with:
          # Owner/name of the registry repository
          registry: skleinbo/JuliaRegistry.jl
          lookback: 28
          # SSH private key for pushing tags
          ssh: ${{secrets.DOCUMENTER_KEY}}
          # Changelog template
          changelog: |
            This is release {{ version }} of {{ package }}.
            {% if custom %}
            Here are my release notes!
            {{ custom }}
            {% endif %}
